# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/top_zofu/top_zofu.srcs/sources_1/ip/background_rom/background_rom.xci
# IP: The module: 'background_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/top_zofu/top_zofu.gen/sources_1/ip/background_rom/background_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/top_zofu/top_zofu.srcs/sources_1/ip/background_rom/background_rom.xci
# IP: The module: 'background_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/top_zofu/top_zofu.gen/sources_1/ip/background_rom/background_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
